photoproject/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
#URLパターンを登録するための変数
urlpatterns = [
#サインアップページのビューの呼び出し
  path('signup/',
       views.SignUpView.as_view(),
       name='signup'),

#サインアップ完了ページのビューの呼び出し
  path('signup_success/',
       views.SignUpSuccessView.as_view(),
       name='signup_success'),
]

photoproject/photo/urls.py
from django.urls import path
from . import views

app_name ='photo'

urlpatterns = [
  path('',views.IndexView.as_view(),name='index'),
]

photoproject/photoproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('photo.urls')),
    path('',include('accounts.urls')),
]

photoproject/accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
# Create your models here.
class CustomUser(AbstractUser):
  pass

photoproject/photo/models.py
from django.db import models

# Create your models here.

photoproject/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUsertionForm(UserCreationForm):
  model = CustomUser
  fields = ('username','email','password1','passwors2')
  
class Meta:
    pass

photoproject/accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView,TemplateView
from .forms import CustomUsertionForm
from django.urls import reverse_lazy

class SignUpView(CreateView):#サインアップページのビュー

  from_class = CustomUsertionForm
  template_name = "signup.html"
  success_url = reverse_lazy('accounts:signup_success')

  def from_vaild(self,form):#formオブジェクトのフィールドの値をデータベースに保存
    user = form.save()
    self.object = user
    return super().form_valid(form)#戻り値はスーパークラスのform_validの戻り値
  
class SignUpSuccessView(TemplateView):#サインアップ完了ページのビュー
  template_name = "acocunt/signup_success.html"#レンダリングるするテンプレート

# Create your views here.

photoproject/photo/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class IndexView(TemplateView):
  template_name ='index.html'

photoproject/accounts/templates/signup.html
{% extends " 'bese.html" %}

{% block  title %}Sign up{% endblock %}

  {% block contents%}
  <hr>
  <div class="container">
    <div class="row">
      <div class="col offset-2">
          <h3>サインアップ</h3>
          <form method = "post">
            {% csrf_token %}

            {% for field in from %}
            <p>
              {{field.label_tag}}<br>
              {{field}}

              {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
              {% endif %}

              {% for error in field.errors %}
                <p style="color: red">{{error}}</p>
              {% endfor%}
            </p>
            {% endfor %}
            <p style="color:red">
              ※メールアドレスはパスワードをリセットする際に必要になりますので、登録をお願いします。
            </p>

            <input type="submit" value="Sign up">
          </form>

          <br>
          <p><a href="{% url 'photo:index' %}">
            登録をやめてトップページに戻る</a>
          </p>
        </div>
      </div>
  </div>
  {% endblock %}

photoproject/accounts/templates/signup_success.html
{% extends 'bese.html'%}<!-- ベーステンプレートを適用する-->

{% block title %}Registration Complete{% endblock %}
{% block contents%}

<div class="container">
<!--行の配置-->
  <div class="row">
    <div class="col offset-4 py-4">
      <h3>登録が完了しました</h3>
      <p><a href="#">ログインはこちら</a><p>
    </div>
  </div>
</div>
{% endblock %}

photoproject/photo/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{% block title%}{% endblock %}</title>

    <!--Bootstrap core CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
                rel="atylesheet"
                integrity="sha384-EVSTQN3/azprGlAnm3QDgpJLIm9Nao0YzFspd3yD65VohhpuuCOmLASjC"
                crossorigin="anonymous"
>    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>

  <body>
    {% comment %} <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div> {% endcomment %}

    <!--ページのヘッダー-->
  <header>
<!--ナビゲーションバーのヘッダー-->
        <div class="collapse bg-dark" id="navbarHeader">
          <div class="container">
            <div class="row">
              <div class="col-sm-8 col-md-7 py-4">
              <!--ヘッダーのタイトルと本文-->

                <h4 class="text-while">お気に入りを見つけよう</h4>
                <p class="text-muted">
                  だれでも参加できる写真投稿サイトです
                  自分で撮影した写真なら何でもオッケー!
                  でも、カテゴリに属する写真に限ります。
                  コメントもつけてください
                </p>
              </div>
              <div class="col-sm-4 offset-md-1 py-4">
                <h4 class="text-white">Contact</h4>
                <ul class="list-unstyled">
                  <li><a href="#" class="text-white">サインアップ</a></li>
                  <li><a href="#" class="text-white">ログイン</a></li>
                  <li><a href="mailto:admin@example.com" class="text-white">Email me</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
          <div class="container">

          <!--トップページへのリンク-->
            <a href="{% url 'photo:index' %}" 
              class="navbar-brand d-flex align-items-center">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
              <strong>Photo Gallery</strong>
            </a>
            <!--トグルボタン-->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
        </div>
      </header>

      <!--main-->
      <main>
        {% block contents%}{% endblock %}
      </main>

      <!--フッター-->
      <footer class="text-body-secondary py-5">
        <div class="container">
          <p class="float-end mb-1">
            <a href="#">Back to top</a>
          </p>
          <p class="mb-1">Photo Gallery is &copy Bootstrap, but please post a lot!</p>
        </div>
      </footer>
      
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
              integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
              crossorigin="anonymous"></script>

    </body>
</html>

photoproject/photo/templates/index.html
{% extends 'base.html' %}

{% block title %}Photo Gallery{% endblock %}

  {% block contents %}

  {%  include "photos_title.html" %}

  {% include "photos_list.html" %}

  {% endblock %}

photoproject/photo/templates/photos_list.html
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
              <title>Placeholder</title>
              <rect width="100%" height="100%" fill="#55595c"/>
            </svg>

            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" 
                    class="btn btn-sm btn-outline-secondary">
                    View</button>

                  <button type="button" 
                    class="btn btn-sm btn-outline-secondary">
                    Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

photoproject/photo/templates/photos_title.html
<!--タイトルとナビゲーションボタン-->
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
      
        <h1 class="fw-light">Photo Gallery</h1>
        <p class="lead text-muted">
            コメントをみて写真に描かれた世界に思いを馳せましょう
            素敵な写真とコメントをお待ちしています</p>
        <p>
          <a href="#" class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="#" class="btn btn-secondary my-2">登録済みの方はログイン</a>
        </p>
      </div>
    </div>
  </section>